services:
  - type: web
    name: nDrims-project-LAM
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python Api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
